// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Asset.Domain.Models;

[Index("AssetName", Name = "IX_Assets_AssetName")]
[Index("AssignedEmployeeId", Name = "IX_Assets_AssignedEmployeeId")]
[Index("LocationId", Name = "IX_Assets_LocationId")]
[Index("Manufacturer", "AssetTypeId", Name = "IX_Assets_Manufacturer_AssetTypeId")]
[Index("Status", "DepartmentId", Name = "IX_Assets_Status_DepartmentId")]
[Index("AssetCode", Name = "UQ_Assets_AssetCode", IsUnique = true)]
public partial class Asset
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string AssetCode { get; set; }

    [Required]
    [StringLength(200)]
    public string AssetName { get; set; }

    [StringLength(1000)]
    public string Description { get; set; }

    public int CategoryId { get; set; }

    public int AssetTypeId { get; set; }

    [StringLength(100)]
    public string Manufacturer { get; set; }

    [StringLength(100)]
    public string Model { get; set; }

    [StringLength(100)]
    public string SerialNumber { get; set; }

    public int? DepartmentId { get; set; }

    public int? AssignedEmployeeId { get; set; }

    public int? LocationId { get; set; }

    public int Status { get; set; }

    public DateOnly? PurchaseDate { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? PurchaseCost { get; set; }

    public DateOnly? WarrantyExpiryDate { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }

    public DateTime CreatedAt { get; set; }

    [StringLength(450)]
    public string CreatedByUserId { get; set; }

    public DateTime? UpdatedAt { get; set; }

    [StringLength(450)]
    public string UpdatedByUserId { get; set; }

    public DateTime? RetiredAt { get; set; }

    [StringLength(500)]
    public string RetirementReason { get; set; }

    [StringLength(450)]
    public string RetiredByUserId { get; set; }

    [InverseProperty("Asset")]
    public virtual ICollection<AssetTransfer> AssetTransfers { get; set; } = new List<AssetTransfer>();

    [ForeignKey("AssetTypeId")]
    [InverseProperty("Assets")]
    public virtual AssetType AssetType { get; set; }

    [ForeignKey("AssignedEmployeeId")]
    [InverseProperty("Assets")]
    public virtual Employee AssignedEmployee { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Assets")]
    public virtual Category Category { get; set; }

    [ForeignKey("DepartmentId")]
    [InverseProperty("Assets")]
    public virtual Department Department { get; set; }

    [ForeignKey("LocationId")]
    [InverseProperty("Assets")]
    public virtual Location Location { get; set; }
}