// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Asset.Domain.Models;

[Index("AssetId", "TransferDate", Name = "IX_AssetTransfers_AssetId_TransferDate", IsDescending = new[] { false, true })]
[Index("TransferredByUserId", Name = "IX_AssetTransfers_TransferredByUserId")]
public partial class AssetTransfer
{
    [Key]
    public int Id { get; set; }

    public int AssetId { get; set; }

    public int? FromEmployeeId { get; set; }

    public int? ToEmployeeId { get; set; }

    public int? FromDepartmentId { get; set; }

    public int? ToDepartmentId { get; set; }

    public int? FromLocationId { get; set; }

    public int? ToLocationId { get; set; }

    public DateTime TransferDate { get; set; }

    [Required]
    [StringLength(500)]
    public string Reason { get; set; }

    [Required]
    public string TransferredByUserId { get; set; }

    [ForeignKey("AssetId")]
    [InverseProperty("AssetTransfers")]
    public virtual Asset Asset { get; set; }

    [ForeignKey("FromDepartmentId")]
    [InverseProperty("AssetTransferFromDepartments")]
    public virtual Department FromDepartment { get; set; }

    [ForeignKey("FromEmployeeId")]
    [InverseProperty("AssetTransferFromEmployees")]
    public virtual Employee FromEmployee { get; set; }

    [ForeignKey("FromLocationId")]
    [InverseProperty("AssetTransferFromLocations")]
    public virtual Location FromLocation { get; set; }

    [ForeignKey("ToDepartmentId")]
    [InverseProperty("AssetTransferToDepartments")]
    public virtual Department ToDepartment { get; set; }

    [ForeignKey("ToEmployeeId")]
    [InverseProperty("AssetTransferToEmployees")]
    public virtual Employee ToEmployee { get; set; }

    [ForeignKey("ToLocationId")]
    [InverseProperty("AssetTransferToLocations")]
    public virtual Location ToLocation { get; set; }
}