// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Asset.Domain.Models;

[Index("CategoryName", Name = "UQ_Categories_CategoryName", IsUnique = true)]
public partial class Category
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string CategoryName { get; set; }

    [StringLength(500)]
    public string Description { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("Category")]
    public virtual ICollection<Asset> Assets { get; set; } = new List<Asset>();
}