// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Asset.Domain.Models;

[Index("Code", Name = "UQ_Departments_Code", IsUnique = true)]
public partial class Department
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(150)]
    public string DepartmentName { get; set; }

    [Required]
    [StringLength(20)]
    public string Code { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("FromDepartment")]
    public virtual ICollection<AssetTransfer> AssetTransferFromDepartments { get; set; } = new List<AssetTransfer>();

    [InverseProperty("ToDepartment")]
    public virtual ICollection<AssetTransfer> AssetTransferToDepartments { get; set; } = new List<AssetTransfer>();

    [InverseProperty("Department")]
    public virtual ICollection<Asset> Assets { get; set; } = new List<Asset>();

    [InverseProperty("Department")]
    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}