// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Asset.Domain.Models;

[Index("DepartmentId", Name = "IX_Employees_DepartmentId")]
[Index("FullName", Name = "IX_Employees_FullName")]
[Index("EmployeeCode", Name = "UQ_Employees_EmployeeCode", IsUnique = true)]
public partial class Employee
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(30)]
    public string EmployeeCode { get; set; }

    [Required]
    [StringLength(200)]
    public string FullName { get; set; }

    [StringLength(256)]
    public string Email { get; set; }

    [StringLength(30)]
    public string Phone { get; set; }

    public int DepartmentId { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("FromEmployee")]
    public virtual ICollection<AssetTransfer> AssetTransferFromEmployees { get; set; } = new List<AssetTransfer>();

    [InverseProperty("ToEmployee")]
    public virtual ICollection<AssetTransfer> AssetTransferToEmployees { get; set; } = new List<AssetTransfer>();

    [InverseProperty("AssignedEmployee")]
    public virtual ICollection<Asset> Assets { get; set; } = new List<Asset>();

    [ForeignKey("DepartmentId")]
    [InverseProperty("Employees")]
    public virtual Department Department { get; set; }
}