// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Asset.Domain.Models;

[Index("LocationName", Name = "UQ_Locations_LocationName", IsUnique = true)]
public partial class Location
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(150)]
    public string LocationName { get; set; }

    [StringLength(300)]
    public string Address { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("FromLocation")]
    public virtual ICollection<AssetTransfer> AssetTransferFromLocations { get; set; } = new List<AssetTransfer>();

    [InverseProperty("ToLocation")]
    public virtual ICollection<AssetTransfer> AssetTransferToLocations { get; set; } = new List<AssetTransfer>();

    [InverseProperty("Location")]
    public virtual ICollection<Asset> Assets { get; set; } = new List<Asset>();
}