// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Asset.Domain.Models;

[Keyless]
public partial class vw_AssetSearch
{
    public int AssetId { get; set; }

    [Required]
    [StringLength(50)]
    public string AssetCode { get; set; }

    [Required]
    [StringLength(200)]
    public string AssetName { get; set; }

    [StringLength(100)]
    public string Manufacturer { get; set; }

    [StringLength(100)]
    public string Model { get; set; }

    [StringLength(100)]
    public string SerialNumber { get; set; }

    public int StatusId { get; set; }

    [Required]
    [StringLength(17)]
    public string Status { get; set; }

    public DateOnly? PurchaseDate { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? PurchaseCost { get; set; }

    public DateOnly? WarrantyExpiryDate { get; set; }

    [Required]
    [StringLength(100)]
    public string CategoryName { get; set; }

    [Required]
    [StringLength(100)]
    public string AssetType { get; set; }

    [StringLength(150)]
    public string DepartmentName { get; set; }

    [StringLength(200)]
    public string AssignedEmployee { get; set; }

    [StringLength(150)]
    public string LocationName { get; set; }
}